### PR TITLE
Autolaunch ROS at power-on

### PR DESCRIPTION
**Pull request by mattp256**
Adding capability to launch ROS/WheelE automatically at power-on using systemd

CentralIllinoisRoboticsClub/wheele Issue #18

### CODE REVIEW

**Review by coderkarl — CHANGES_REQUESTED** [review]
The username is circ (not pi) for the current wheele rpi image.
Can we use $username in all files to keep it modular?

Should we have this tested on wheele by Mike before merging it?
One question I have is if we need to wait for the CAN initialization on the pi before launching.
I'll have to review where I automatically initialized CAN when the pi boots up.

**Comment by coderkarl** [comment]
We could just add this command before the roslaunch command:
sudo ip link set can0 up type can bitrate 500000

That way CAN is setup automatically in the same place and documented here.
We can find where I put it and just remove it from there.

**Comment by coderkarl** [comment]
@MikeDvorsky Can you look at the wheele pi files and figure out which method I used to setup CAN at startup?
https://www.dexterindustries.com/howto/run-a-program-on-your-raspberry-pi-at-startup/

**Comment by mattp256** [comment]
Testing before merging - yes, agree. Mike and I talked about that too. I can help as necessary.

There does not seem to be a straight forward way to use $username across multiple files unfortunately.  I'd propose just changing to circ and rolling with it for now. 

For the can0 link, I think it would make more sense to start it up separately from ROS. Shouldn't it be possible to configure that to startup by default without having to run the ip command? There should be something like /etc/sysconfig/network-scripts/ifcfg-can0 and/or /etc/networking/interfaces for this. Would have to poke around a little on the pi but there should be a way to do it.

**Comment by mattp256** [comment]
Since Josh suggested adding an install script, I did find a way to set the username (and ros distro) at install time, instead of hard-coding it into the scripts, so the install should be pretty modular now. See latest commit.

**Comment by MikeDvorsky** [comment]
CAN setup is done from /etc/rc.local

**Comment by coderkarl** [comment]
For setting up the can0 network via network interfaces, reference:
https://www.embeddedpi.com/documentation/isolated-canbus/mypi-industrial-raspberry-pi-can-bus-card-configuration
This also explains the changes needed in /boot/config.txt

**Comment by mattp256** [comment]
Made some tweaks during build session but latest commit seems to be working well

**Review by coderkarl — APPROVED** [review]

**Pull request merged**
